module.exports = {
  extends: ['stylelint-config-standard'],
  overrides: [
    {
      files: ['**/*.styled.ts', '**/*.styled.tsx'],
      customSyntax: '@stylelint/postcss-css-in-js',
    },
  ],
  rules: {
    'no-empty-source': null,
    'property-no-unknown': [
      true,
      {
        ignoreProperties: [
          'tintColor',
          'resizeMode',
          'flexGrow',
          'shadowColor',
          'shadowOffset',
          'shadowOpacity',
          'shadowRadius',
          'paddingHorizontal',
          'paddingVertical',
          'marginHorizontal',
          'marginVertical',
          'borderTopLeftRadius',
          'borderTopRightRadius',
          'borderBottomLeftRadius',
          'borderBottomRightRadius',
          'textAlignVertical',
          'textShadowColor',
          'textShadowOffset',
          'textShadowRadius',
          'elevation',
          'includeFontPadding',
          'writingDirection',
          'fontVariant',
          'textDecorationLine',
          'textDecorationStyle',
          'textDecorationColor',
          'textTransform',
          'letterSpacing',
          'fontFeatureSettings',
          'fontVariantLigatures',
          'fontKerning',
          'fontStretch',
          'fontSynthesis',
          'fontVariantCaps',
          'fontVariantEastAsian',
          'fontVariantNumeric',
          'fontVariantPosition',
          'textEmphasisColor',
          'textEmphasisPosition',
          'textEmphasisStyle',
          'textOrientation',
          'textRendering',
          'textSizeAdjust',
          'userSelect',
          'wordBreak',
          'wordSpacing',
          'wordWrap',
          'writingMode',
          'paddingHorizontal',
          'paddingVertical',
          'marginHorizontal',
          'marginVertical',
          'borderTopLeftRadius',
          'borderTopRightRadius',
          'borderBottomLeftRadius',
          'borderBottomRightRadius',
          'textAlignVertical',
          'textShadowColor',
          'textShadowOffset',
          'textShadowRadius',
          'elevation',
          'includeFontPadding',
          'marginBottom',
          'marginTop',
          'marginLeft',
          'marginRight',
          'paddingLeft',
          'paddingRight',
          'paddingTop',
          'paddingBottom',
          'borderWidth',
          'borderColor',
          'borderStyle',
          'borderRadius',
          'justifyContent',
          'alignItems',
          'flexDirection',
          'flexWrap',
          'flexGrow',
          'flexShrink',
          'flexBasis',
          'fontFamily',
          'fontSize',
          'fontWeight',
          'fontStyle',
          'textAlign',
          'textDecoration',
          'backgroundColor',
          'alignSelf',
          'lineHeight',
        ]
      }
    ],
    'unit-no-unknown': null,
    'selector-type-no-unknown': null,
    'font-family-no-missing-generic-family-keyword': null,
  },
};